#!/usr/bin/env bash

# Copyright (c) 2016 Andrew Moll 
# 
# This program is free software: you can redistribute it and/or modify  
# it under the terms of the GNU General Public License as published by  
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but 
# WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License 
# along with this program. If not, see <http://www.gnu.org/licenses/>.

[ "linux-gnu" = "$OSTYPE" ] && LOG_DATE_FORMAT="%Y-%m-%dT%H:%M:%S.%3NZ" || LOG_DATE_FORMAT="%Y-%m-%dT%H:%M:%SZ"
LOG_INFO=true
LOG_DEBUG=true

function log() {
    local LEVEL="$1"; shift;
    echo $(date -u +"$LOG_DATE_FORMAT") $(basename "$0")"[$$]" $LEVEL: "$@" 1>&2
}
function log_error() {                        log ERROR "$@"; }
function log_warn()  {                        log WARN  "$@"; }
function log_info()  { [ -n "$LOG_INFO"  ] && log INFO  "$@"; }
function log_debug() { [ -n "$LOG_DEBUG" ] && log DEBUG "$@"; }
